---
- name: install and start nginx
  hosts: myvm

  tasks:
  - name: install nginx
    zypper: 
      name: nginx 
      state: present
  - name: start nginx
    service: 
      name: nginx 
      state: started